employee/app1/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views
app_name='app1'

urlpatterns = [
    path('admin/',admin.site.urls),
    path('',views.home,name="home"),
    path('add',views.add,name="add")
   ]

employee/employee/urls.py
from django.contrib import admin
from django.urls import path,include
from app1 import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
]

if settings.DEBUG:
    urlpatterns = static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

employee/app1/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):

    emp_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=100)
    email=models.EmailField()
    phone=models.IntegerField()
    designation=models.CharField(max_length=50)
    salary=models.IntegerField()
    image=models.ImageField(upload_to="employees")

employee/app1/forms.py
from app1.models import Employee
from django import forms

class Employeeform(forms.ModelForm):
    class Meta:
        model=Employee
        fields="__all__"

employee/app1/views.py
from django.shortcuts import render, redirect
from app1.forms import Employeeform
from app1.models import Employee
# Create your views here.
def home(request):
    b=Employee.object.all()
    context={'employee':b}
    return render(request,'home.html',context)

def add(request):
    if request.method=='POST':
        f=Employeeform(request.POST,request.FILES)
        if f.is_valid():
            f.save()
            return redirect('app1:add')

    if request.method=='GET':
        f=Employeeform()
        context={"form":f}
        return render(request,'add.html',context)

# def view(request):
#     if request.method=="GET":
#         f=Employee.objects.all()
#         context={'form':f}
#         return render(request,'view.html',context)

employee/templates/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
  {% block title %}

  {% endblock %}
{% block content %}
<div class="container w-50 p-5 mt-5 bg-light text-center shadow">
  <h1>employee records</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}

    <div class="mb-3">
      <input type="submit">
    </div>
  </form>
</div>
{% endblock %}

employee/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  {% block title %}
    <title>Title</title>
  {% endblock %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand fs-1 fst-italic" href="#">Employee</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active fs-3" aria-current="page" href="{% url 'app1:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active fs-3" href="{% url 'app1:add' %}">employee</a>
        </li>
      </ul>
  </div>
  </div>
   </nav>
{% block content %}
<div class="container w-50 p-5 mt-5 bg-light text-center shadow">

</div>
{% endblock %}
</body>
</html>

employee/templates/home.html
{% extends 'base.html' %}
  {% block title %}

  {% endblock %}
{% block content %}
<div class="container w-100 p-5 mt-5 bg-light text-center shadow">
  <h1>welcome to employee records</h1>
  <table class="table table-bothered table-primary">
    <tr>
        <th>img</th>
        <th>emp_id</th>
        <th>emp_name</th>
        <th>email</th>
        <th>phone_no</th>
        <th>designation</th>
        <th>salary</th>
    </tr>
    {% for i in employee %}
    <tr>
        <td><img src="{{i.image.url}}" height="100px" width="100px"></td>
        <td>{{i.emp_id}}</td>
        <td>{{i.emp_name}}</td>
        <td>{{i.email}}</td>
        <td>{{i.phone_no}}</td>
        <td>{{i.designation}}</td>
        <td>{{i.salary}}  </td>
    </tr>
{% endfor %}
 </table>
</div>
    {% endblock %}

employee/templates/view.html
<!--{% extends 'base.html' %}-->

<!--    {% block button %}-->
<!--              <div class="collapse navbar-collapse" id="navbarSupportedContent" >-->
<!--      <ul class="navbar-nav me-auto mb-2 mb-lg-0">-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link active" aria-current="page" href="{% url 'app1:home' %}">Home</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'app1:add' %}">ADD EMPLOYEES</a>-->
<!--        </li>-->

<!--      </ul>-->
<!--    </div>-->
<!--      {% endblock %}-->
<!--{% block content %}-->
<!--<div class="container d-flex justify-content-center w-75 border border-1 shadow p-3 mt-4">-->
<!--<table class="table table-bordered">-->
<!--    <tr>-->
<!--        <th>Emp_id</th>-->
<!--        <th>Photo</th>-->
<!--        <th>Name</th>-->
<!--        <th>email</th>-->
<!--        <th>Phone</th>-->
<!--        <th>Designation</th>-->
<!--        <th>Salary</th>-->
<!--    </tr>-->
<!--{% for i in form %}-->
<!--    <tr>-->
<!--        <td>{{i.id}}</td>-->
<!--        <td><img src="{{i.image.url}}" style="height:100px; width:100px"></td>-->
<!--        <td>{{i.name}}</td>-->
<!--        <td>{{i.email}}</td>-->
<!--        <td>{{i.phone}}</td>-->
<!--        <td>{{i.designation}}</td>-->
<!--        <td>{{i.salary}}</td>-->
<!--    </tr>-->
<!--{% endfor %}-->
<!--</table>-->
<!--</div>-->
<!--{% endblock %}-->