movie/app1/urls.py
from django.urls import path

from app1 import views


app_name='app1'
urlpatterns = [
    path('',views.movielist,name="movielist"),
    path('addmovie', views.addmovie, name="addmovie"),
    path('moviedetails/<int:i>',views.moviedetails,name='moviedetails'),
    path('update/<int:i>',views.update,name='update'),
    path('delete/<int:i>',views.delete,name='delete'),

]

movie/movie/urls.py
# from django.contrib import admin
# from django.urls import path,include
# from app1 import views
# from django.conf.urls.static import static
# from django.conf import settings
#
#
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('',views.movielist,name='home'),
#     path('addmovie/',views.addmovie,name='addmovie'),
#     path('update/<int:i>', views.update,name='update'),
#     path('delete/<int:i>', views.delete,name='delete')
# ]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


from app1 import views


app_name='app1'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie/app1/models.py
from django.db import models

# Create your models here.

class Moviedetail(models.Model):
     title=models.CharField(max_length=100)
     description=models.TextField()
     language=models.CharField(max_length=100)
     year=models.IntegerField()
     directory=models.CharField(max_length=100)
     image=models.ImageField(upload_to='images')

movie/app1/forms.py
from django import forms
from app1 import models
from app1.models import Moviedetail


class MovieForm(forms.ModelForm):
    class Meta:
        model=Moviedetail
        fields='__all__'

movie/app1/views.py
# from django.shortcuts import render
# from app1.forms import  MovieForm
# from app1.models import Moviedetail
#
#
#
# # Create your views here.
#
# def home(request):
#
#         b=Moviedetail.objects.all()
#         context={"movie":b}
#         return render(request,'movielist.html')
#
#
# def add(request):
#     if(request.method=="POST"):
#         from_instance=MovieForm(request.POST,request.FILES)
#         if from_instance.is_valid():
#            from_instance.save()
#            return render(request,'addmovie.html')
#     if (request.method == "GET"):
#         from_instance=MovieForm(request.GET)
#         context={'form':from_instance}
#         return render(request, 'addmovie.html',context)


from django.shortcuts import render, redirect

from app1.forms import MovieForm
from app1.models import Moviedetail

# Create your views here.

def movielist(request):
        b =Moviedetail.objects.all()  # to read all record from table
        context = {'Moviedetail': b}
        return render(request,'movielist.html',context)

def addmovie(request):
    if request.method=="POST": #after submission
        form_instance=MovieForm(request.POST,request.FILES)
        if form_instance.is_valid():
            form_instance.save()
            context={'form':form_instance}
            return render(request,'addmovie.html',context)

    if request.method=="GET":
        form_instance=MovieForm()
        context={'form':form_instance}
        return  render(request,'addmovie.html',context)

def moviedetails(request,i):
    if request.method=="GET":
        b=Moviedetail.objects.get(id=i)
        context={'movie':b}
        return render(request,'moviedetails.html',context)

def update(request,i):
    if request.method=="POST":
        b=Moviedetail.objects.get(id=i)
        form_instance=MovieForm(request.POST,request.FILES,instance=b)
        if form_instance.is_valid():
            form_instance.save()
            redirect('app1:movielist')

    if request.method=="GET":
        b=Moviedetail.objects.get(id=i)
        form_instance=MovieForm(instance=b)
        context={'movie':form_instance}
        return render(request,'update.html',context)

def delete(request,i):
    b=Moviedetail.objects.get(id=i)
    b.delete()
    return redirect('app1:movielist')

movie/templates/addmovie.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container border border-2 mx-auto text-center mt-5 p-3 w-50 mt-10 h-25">
  <h2>Add Moviedetails</h2>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy }}
  <div class="mb-3">
    <input type="submit" class="btn btn-secondary" >

  </div>

</form>

</div>
{% endblock %}

movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg fw-bold navbar-light text-light p-3 bg-danger">
  <div class="container-fluid">
      <h2>ONLINE MOVIE STORE</h2>
    {% block link %}

    <a class="btn btn-primary" href="{% url 'app1:addmovie' %}">ADD MOVIE</a>
  {% endblock %}
    </div>
</nav>

{% block content %}
<div class="container text-center  mx-auto p-4 mt-5 border border-2px border-danger">

</div>
{% endblock %}

</body>
</html>

movie/templates/moviedetails.html
{% extends 'base.html' %}

{% block content %}
<div class="container mx-auto p-4 mt-5 border border-2px border-primary shadow">
   <h1 class=" text-center "> MOVIE DETAILS</h1>

<div class="card mt-5 mb-3 text-dark" style="width:50%;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{movie.image.url}}" class="img-fluid rounded-start" style="height:250px" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title fs-4 fw-bold">{{movie.title}}</h5>
          <ul>
              <li>{{movie.language}}</li>
              <li>{{movie.description}}</li>
              <li>{{movie.year}}</li>
              <li>{{movie.director}}</li>
          </ul>
        <a href="{% url 'app1:update' movie.id %}" class="btn btn-danger mt-3 ms-5">update</a>
          <a href="{% url 'app1:delete' movie.id %}" class="btn btn-danger mt-3 ms-4">Delete</a>
      </div>
    </div>
  </div>
</div>

</div>
{% endblock %}

movie/templates/movielist.html
{% extends 'base.html' %}

{% block content %}
<div class="container mx-auto p-4 mt-5 border border-2px border-danger">
   <h1 class=" text-center "> MOVIE LIST</h1>

    <div class="row">
        {% for i in Moviedetail %}
        <div class="col-3">
<div class="card shadow mx-auto text-dark mt-4 mb-4">
    <img src="{{i.image.url}}" height="200px" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title   text-center ">{{i.title}}</h5>
      <p class="card-text">
          <ul>
      <li> {{i.year}}</li>
      <li>{{i.language}}</li>
  </ul>
      <a href="{% url 'app1:moviedetails' i.id %}" class="btn btn-danger">View</a>
  </div>
    </div>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

movie/templates/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    <title></title>
  {% endblock %}

{% block content %}
<div class="container text-center mx-auto mt-5 p-4 border border-2px border-danger">

<h1>EDIT BOOK</h1>
        <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{movie|crispy}}
        <div class="mt-3">
            <input type="submit" class="btn btn-primary">
        </div>
    </form>
</div>

{% endblock %}