multiuserotp/multiuser/urls.py
from django.contrib import admin
from django.urls import path,include

app_name='users'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
]

multiuserotp/users/urls.py
from django.urls import path
from users import  views



app_name='users'

urlpatterns = [

    path('',views.Home.as_view(),name='home'),
    path('register',views.Register.as_view(),name='register'),
    path('login',views.Userlogin.as_view(),name='login'),
    path('logout',views.Userlogout.as_view(),name='logout'),
    path('adminhome',views.Adminhome.as_view(),name='adminhome'),
    path('studenthome',views.Studenthome.as_view(),name='studenthome'),
    path('teacherhome',views.Teacherhome.as_view(),name='teacherhome'),
    path('otp',views.Otp_verefiction.as_view(),name='otp'),
]

multiuserotp/users/models.py
import random

from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser

class Customuser(AbstractUser):
    phone=models.IntegerField(null=True)
    role=models.CharField(max_length=20,null=True)
    gender=models.CharField(max_length=20,null=True)
    is_verified=models.BooleanField(default=False) #to check weather user acct is verified or not
    otp=models.CharField(max_length=10,null=True)  #to store otp in backend table (CustomUser)


    def generate_otp(self):
        otp=str(random.randint(1000,9999))+str(self.id)
        self.otp=otp
        self.save()

multiuserotp/users/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import Customuser

from django import forms





class SignupForm(UserCreationForm):
    role_choices=(('student','Student'),('teacher','Teacher'))
    role=forms.ChoiceField(choices=role_choices)
    gender_choices=(('male','Male'),('female','Female'))
    gender=forms.ChoiceField(choices=gender_choices,widget=forms.RadioSelect)
    class Meta:
        model=Customuser
        fields=['username','password1','password2','email','first_name','last_name','phone','role','gender']

class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)

multiuserotp/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import logout,login,authenticate
# Create your views here.
from django.views import View
from django.contrib import messages
from users.forms import SignupForm,LoginForm


from django.core.mail import send_mail
from users.models import Customuser

class Home(View):
    def get(self,request):
        return render(request,'home.html')

class Register(View):
    def post(self,request):
        form_instance=SignupForm(request.POST)
        if form_instance.is_valid():
            u=form_instance.save(commit=False)
            u.is_active=False
            u.save()
            u.generate_otp()
            send_mail(
                "Django Auth OTP",
                u.otp,
                "farzeen4049@gmail.com",
                [u.email],
                fail_silently=False,
            )
            return redirect('users:otp')
        else:
            print('invalid credentials ')

            return render(request,'register.html',{'form':form_instance})
    def get(self,request):
        form_instance=SignupForm()
        context={'form':form_instance}
        return render(request,'register.html',context)

class Userlogin(View):
    def get(self,request):
        form_instance=LoginForm()
        context={'form':form_instance}
        return render(request,'login.html',context)

    def post(self,request):
        form_instance = LoginForm(request.POST)
        if form_instance.is_valid():
            u = form_instance.cleaned_data['username']
            p = form_instance.cleaned_data['password']
            user=authenticate(username=u,password=p)
            if user and user.is_superuser==True:
                login(request,user)
                return redirect('users:adminhome')
            elif user and user.role=="student":
                login(request,user)
                return redirect('users:studenthome')
            elif user and user.role=="teacher":
                login(request,user)
                return redirect('users:teacherhome')
            else:
                messages.error(request,'Invalid User')
                return render(request,'login.html',{'form': form_instance})

class Userlogout(View):
    def get(self,request):
        logout(request)
        return redirect('users:login')

class Adminhome(View):
    def get(self,request):
        return render(request,'adminhome.html')

class Studenthome(View):
    def get(self,request):
        return render(request,'studenthome.html')

class Teacherhome(View):
    def get(self,request):
        return render(request,'teacherhome.html')

class Otp_verefiction(View):
    def post(self,request):
        otp=request.POST['otp']
        try:
            u=Customuser.objects.get(otp=otp)
            u.is_verified=True
            u.is_active=True
            u.otp=None
            u.save()
            return redirect('users:login')
        except:
            messages.error(request,'Invalid Otp')
            return redirect('users:otp')

    def get(self,request):
        return render(request,'otp.html')

multiuserotp/templates/adminhome.html
{% extends 'base.html' %}
{% block title %}
<title>Admin</title>
{% endtitle %}


{% block content %}
<div class="container border border-2 text-center border-dark p-5 mt-5">
  <h1>Admin Home</h1>
  {% if user.is_authenticated %}
  {{user.username}}
  {% else %}
  <h4>guest</h4>
  {% endif %}
</div>

{% endblock %}

multiuserotp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body class="bg-secondary">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MultiUser</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'users:home' %}">Home</a>

        {% if user.is_authenticated %}
           <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">logout</a>
        </li>
       {% else %}
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">login</a>
        </li>
       {% endif  %}
      </ul>
      <form class="d-flex">
          <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}

</body>
</html>

multiuserotp/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container border border-2 text-center border-dark p-5 mt-5">
  <h1>Home</h1>
  {% if user.is_authenticated %}
  {{user.username}}
  {% else %}
  <h4>guest</h4>
  {% endif %}
</div>

{% endblock %}

multiuserotp/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container border border-2 w-50 text-center border-dark p-5 mt-5">
 <h1>Login</h1>
<form method="post">
   {% csrf_token %}
   {{form|crispy}}
     <input type="submit">
 </form>

{% if messages %}
<ul type="none">
    {% for i in messages %}
    <li>{{i}}</li>
    {% endfor  %}
</ul>
    {% endif %}
</div>

{% endblock %}

multiuserotp/templates/otp.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container border border-2 w-50 text-center border-dark p-5 mt-5">
 <h1>OTP</h1>
<form method="post">
    {%csrf_token%}
        <div class="mb-3">
        <label>Enter Otp</label>
        <input type="text" name="otp">
    </div>
    <div class="mb-3">
      <input type="submit">
    </div >

 </form>

</div>

{% endblock %}

multiuserotp/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container border border-2 text-center border-dark p-5 mt-5">
 <h1>Register</h1>
 <form method="post">
   {% csrf_token %}
   {{form|crispy}}
     <input type="submit">
 </form>
</div>

{% endblock %}

multiuserotp/templates/studenthome.html
{% extends 'base.html' %}
{% block title %}
<title>Student</title>
{% endtitle %}


{% block content %}
<div class="container border border-2 text-center border-dark p-5 mt-5">
  <h1>Student Home</h1>
<!--  {% if user.is_authenticated %}-->
<!--  {{user.username}}-->
<!--  {% else %}-->
<!--  <h4>guest</h4>-->
<!--  {% endif %}-->
</div>

{% endblock %}

multiuserotp/templates/teacherhome.html
{% extends 'base.html' %}
{% block content %}
<div class="container border border-2 text-center border-dark p-5 mt-5">
  <h1>Teacher Home</h1>
  {% if user.is_authenticated %}
  {{user.username}}
  {% else %}
  <h4>guest</h4>
  {% endif %}
</div>

{% endblock %}